version: '3.1'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: item_db
      MYSQL_USER: item
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
